---
title: "project_2"
author: "Michael Robinson"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Dataset #1 - Gifted an Talented Grades 2018-2019
Question: What is the overall score distrioution?


```{r project_2}
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)

# Load the dataset from the URL
url <- "https://raw.githubusercontent.com/MRobinson112/data_607_project2/main/NYC%20Gifted%20and%20Talented%20Grades%202018-19%20-%20Sheet5.csv"
data <- read.csv(url)

print(data)

data_cleaned <- data%>%
  mutate(Will.you.enroll.there. = as.character(`Will.you.enroll.there.`))

data_cleaned <- data_cleaned %>%
  mutate(`Will.you.enroll.there.` = ifelse(grepl("yes|YES|Yep|Yes|y|Y", `Will.you.enroll.there.`), "Will enroll", "Will not enroll"))

print(data_cleaned)

summary(data_cleaned[, c("Entering.Grade.Level", "OLSAT.Verbal.Score", "OLSAT.Verbal.Percentile", "NNAT.Non.Verbal.Raw.Score", "NNAT.Non.Verbal.Percentile", "Overall.Score")])

#   Overall Score summary
summary(data_cleaned$`Overall Score`)

# Histogram of Overall Score
hist(data_cleaned$`Overall.Score`, main="Overall Score Distribution")






```

# Dataset #2 - a work order process at a manufacturing site
Question: What is the distribution of work order status by Building and Type?

```{r}

library(dplyr)
library(tidyr)
library(tidyxl)
library(ggplot2)


Order_data <- readxl::read_excel("~/Downloads/Example of a work order process at a manufacturing site.xlsx", skip = 1) 
Order_data <- Order_data %>% filter(!is.na(Building) | !is.na(Type))

Order_data <- Order_data %>% fill(Building, Type)

tidy_data <- Order_data %>%
  pivot_longer(cols = -c(Building, Type), names_to = "Work_Order_Status", values_to = "Value")

head(tidy_data) 

# a bar plot to show the distribution of work order status by Building and Type
ggplot(tidy_data, aes(x = Building, fill = Work_Order_Status)) +
  geom_bar(position = "fill") +
  facet_wrap(~ Type) +
  labs(title = "Distribution of Work Order Status by Building and Type",
       y = "Proportion",
       x = "Building") +
  theme_minimal()


```
# Dataset #3 - popularity of babynemes from 1800 to 2008 
Question: Analyze one name popularity over time.

```{r}

library(tidyr)
library(dplyr)
library(ggplot2)

url <- "https://raw.githubusercontent.com/hadley/data-baby-names/master/baby-names.csv"
data <- read.csv(url)

data <- data %>% mutate(id = row_number())

# Clean the dataset
cleaned_data <- data %>%
  gather(key, value, -year, -id) %>%
  spread(key, value)

cleaned_data$percent <- as.numeric(cleaned_data$percent)

print(cleaned_data)

# name to analyze
name_to_analyze <- "Michael"

#selected name
name_data <- cleaned_data %>% filter(name == name_to_analyze)

# plot
ggplot(name_data, aes(x = year, y = percent)) +
  geom_line() +
  labs(title = paste("Popularity Trend for Name:", name_to_analyze),
       y = "Percentage",
       x = "Year") +
  theme_minimal()

```
